run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
